FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_builder_rhel-9-golang-1.24-openshift-4.20 AS builder
WORKDIR /go/src/github.com/kubernetes-csi/external-snapshot-metadata
COPY . .
RUN make build GOFLAGS_VENDOR=-mod=vendor

FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_4.20_base-rhel9
COPY --from=builder /go/src/github.com/kubernetes-csi/external-snapshot-metadata/bin/csi-snapshot-metadata /usr/bin/
ENTRYPOINT ["/usr/bin/csi-snapshot-metadata"]
