FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-4.23 AS builder
WORKDIR /go/src/github.com/kubernetes-csi/external-snapshot-metadata
COPY . .
RUN make build GOFLAGS_VENDOR=-mod=vendor

FROM registry.ci.openshift.org/ocp/4.23:base-rhel9
COPY --from=builder /go/src/github.com/kubernetes-csi/external-snapshot-metadata/bin/csi-snapshot-metadata /usr/bin/
ENTRYPOINT ["/usr/bin/csi-snapshot-metadata"]
